import tkinter as tk
from tkinter import ttk
from tkinter import scrolledtext

from utils import easedtimings, tkevents

class EasedTimings(ttk.Frame):
    def __init__(self, master, *args, **kwargs):
        super().__init__(master, *args, **kwargs)
        self.bind_class("Text","<Control-a>", tkevents.selectall)
        tk.Label(self, text="Initial timing:").grid(column=0, row=0)
        self.from_timing = tk.Spinbox(self, from_=-(2<<64), to=2<<64, width=5)
        self.from_timing.grid(column=1, row=0)
        self.from_timing.delete("0", "end")
        self.from_timing.insert("0", "0")
        tk.Label(self, text="Initial BPM:").grid(column=0, row=1)
        self.from_bpm = tk.Spinbox(self, from_=-(2<<64), to=2<<64, increment=0.01, width=5)
        self.from_bpm.grid(column=1, row=1)
        self.from_bpm.delete("0", "end")
        self.from_bpm.insert("0", "0")
        tk.Label(self, text="End timing:").grid(column=0, row=2)
        self.to_timing = tk.Spinbox(self, from_=-(2<<64), to=2<<64, width=5)
        self.to_timing.grid(column=1, row=2)
        self.to_timing.delete("0", "end")
        self.to_timing.insert("0", "600")
        tk.Label(self, text="End BPM:").grid(column=0, row=3)
        self.to_bpm = tk.Spinbox(self, from_=-(2<<64), to=2<<64, increment=0.01, width=5)
        self.to_bpm.grid(column=1, row=3)
        self.to_bpm.delete("0", "end")
        self.to_bpm.insert("0", "100")
        tk.Label(self, text="Parts:").grid(column=0, row=4)
        self.parts = tk.Spinbox(self, from_=2, to=64, width=5)
        self.parts.grid(column=1, row=4)
        self.parts.delete("0", "end")
        self.parts.insert("0", "4")
        tk.Label(self, text="Beatline \nDensity:").grid(column=0, row=5)
        self.beatline = tk.Spinbox(self, from_=-(2<<64), to=2<<64, increment=0.01, width=5)
        self.beatline.grid(column=1, row=5)
        self.beatline.delete("0", "end")
        self.beatline.insert("0", "4.00")
        tk.Label(self, text="Easings:").grid(column=0, row=6)
        self.easing = ttk.Combobox(self, values=["s", "b", "si", "so", "qi", "qo", "ci", "co"], width=5)
        self.easing.grid(column=1, row=6)
        self.easing.delete("0", "end")
        self.easing.insert("0", "s")
        convert = tk.Button(self, text="Convert", command=self.convert)
        convert.grid(column=2, row=6)
        tk.Label(self, text="Output:").grid(column=0, row=7)
        self.outputtiming = scrolledtext.ScrolledText(self, width=50, height=10)
        self.outputtiming.grid(column=1, row=7)
        self.pack()
    def convert(self):
        self.outputtiming.delete("1.0","end")
        t1 = int(self.from_timing.get())
        t2 = int(self.to_timing.get())
        from_bpm = float(self.from_bpm.get())
        to_bpm = float(self.to_bpm.get())
        parts = int(self.parts.get())
        beatline = float(self.beatline.get())
        easing = self.easing.get()
        self.outputtiming.insert("end", easedtimings.easedtimings(t1, t2, from_bpm, to_bpm, parts, easing, beatline))